"""
mp3_to_header.py

Turns an MP3 file into src/audio_sample.h, a C byte array the mp3test
firmware plays out of flash. Lets you test the speaker and MP3 decoder
without WiFi, the camera, or the server.

Usage, from the firmware folder:
    python tools/mp3_to_header.py ..\\server\\audio_output\\reply_xxx.mp3

Keep the file short — it's compiled into the app partition, so anything
past a few hundred KB won't fit alongside the rest of the firmware. A
couple of seconds of speech at a low bitrate is ideal.
"""

import os
import sys

MAX_BYTES = 400_000
HEADER_NAME = "audio_sample.h"


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python tools/mp3_to_header.py <file.mp3>")
        sys.exit(1)

    mp3_path = sys.argv[1]
    if not os.path.isfile(mp3_path):
        print(f"Can't find {mp3_path}")
        sys.exit(1)

    data = open(mp3_path, "rb").read()
    if not data:
        print(f"{mp3_path} is empty")
        sys.exit(1)
    if len(data) > MAX_BYTES:
        print(f"{mp3_path} is {len(data)} bytes — too big to compile in "
              f"(limit {MAX_BYTES}). Use a shorter clip.")
        sys.exit(1)

    src_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src")
    out_path = os.path.normpath(os.path.join(src_dir, HEADER_NAME))

    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("  " + " ".join(f"0x{b:02x}," for b in chunk))

    with open(out_path, "w") as f:
        f.write("// Generated by tools/mp3_to_header.py — do not edit by hand.\n")
        f.write(f"// Source: {os.path.basename(mp3_path)} ({len(data)} bytes)\n")
        f.write("#pragma once\n\n#include <Arduino.h>\n\n")
        f.write(f"const unsigned int AUDIO_SAMPLE_MP3_LEN = {len(data)};\n")
        f.write("const unsigned char AUDIO_SAMPLE_MP3[] = {\n")
        f.write("\n".join(lines))
        f.write("\n};\n")

    print(f"Wrote {out_path} ({len(data)} bytes from {os.path.basename(mp3_path)})")


if __name__ == "__main__":
    main()
