"""
wav_to_header.py — turns a WAV into src/offline_message.h, a C array of
16 kHz mono 16-bit samples that firmware plays straight from flash.

Usage, from the firmware folder:
    python tools/wav_to_header.py assets/offline_message.wav
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "server"))
import pcm  # noqa: E402  (reuses the server's converter)

MAX_BYTES = 300_000  # ~9 s; keeps the app partition comfortable


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python tools/wav_to_header.py <file.wav>")
        sys.exit(1)

    wav = open(sys.argv[1], "rb").read()
    data = pcm.wav_to_pcm(wav)   # forces 16 kHz / mono / 16-bit
    if len(data) > MAX_BYTES:
        print(f"{len(data)} bytes is too long (limit {MAX_BYTES}). Shorten the message.")
        sys.exit(1)

    samples = [int.from_bytes(data[i:i + 2], "little", signed=True)
               for i in range(0, len(data) - 1, 2)]

    out = os.path.normpath(os.path.join(HERE, "..", "src", "offline_message.h"))
    with open(out, "w") as f:
        f.write("// Generated by tools/wav_to_header.py — do not edit by hand.\n")
        f.write(f"// Source: {os.path.basename(sys.argv[1])}, "
                f"{len(samples) / pcm.TARGET_RATE:.1f}s\n")
        f.write("#pragma once\n#include <Arduino.h>\n\n")
        f.write(f"static const size_t OFFLINE_MSG_SAMPLES = {len(samples)};\n")
        f.write("static const int16_t OFFLINE_MSG[] PROGMEM = {\n")
        for i in range(0, len(samples), 16):
            f.write("  " + ",".join(str(s) for s in samples[i:i + 16]) + ",\n")
        f.write("};\n")
    print(f"Wrote {out}: {len(samples)} samples, {len(data)} bytes")


if __name__ == "__main__":
    main()